"use client";

import { useState } from "react";
import { Download, Loader2 } from "lucide-react";
import { s3Api } from "@/lib/s3";
import { cn } from "@/lib/utils";

type Phase = "idle" | "loading" | "error";

type Props = {
  /** S3 object key to download */
  objectKey: string;
  /** Suggested file name for the browser download dialog */
  fileName?: string;
  /** Extra CSS classes */
  className?: string;
};

/**
 * Downloads a file via a presigned URL generated by the server.
 *
 * Fetches the URL, then programmatically triggers a browser download —
 * no direct exposure of S3 credentials to the client.
 */
export function DownloadButton({ objectKey, fileName, className }: Props) {
  const [phase, setPhase] = useState<Phase>("idle");
  const [error, setError] = useState<string | null>(null);

  async function handleDownload() {
    setPhase("loading");
    setError(null);
    try {
      const { url } = await s3Api.download(objectKey, {
        fileName: fileName ?? objectKey.split("/").pop(),
      });
      // Open the presigned URL in a new tab — browser handles the download
      const a = document.createElement("a");
      a.href = url;
      a.download = fileName ?? objectKey.split("/").pop() ?? objectKey;
      a.rel = "noopener noreferrer";
      a.click();
      setPhase("idle");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Download failed");
      setPhase("error");
    }
  }

  return (
    <div className="flex flex-col gap-1">
      <button
        onClick={handleDownload}
        disabled={phase === "loading"}
        className={cn(
          "inline-flex items-center gap-2 rounded-md border border-border bg-background px-4 py-2 text-sm font-medium",
          "hover:bg-accent hover:text-accent-foreground transition-colors",
          "disabled:pointer-events-none disabled:opacity-50",
          className,
        )}>
        {phase === "loading" ? (
          <Loader2 className="size-4 animate-spin" />
        ) : (
          <Download className="size-4" />
        )}
        {phase === "loading" ? "Preparing…" : "Download"}
      </button>
      {error && <p className="text-xs text-destructive">{error}</p>}
    </div>
  );
}
